server:
  port: 8096

spring:
  application:
    name: ExCoupon

  thymeleaf:
    cache: false
    prefix: classpath:templates/views/


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db326?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: user326
    password: 1234

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
